In [32]:
import pandas as pd
pd.options.display.max_columns = None
import numpy as np
import re
import random as random

In [4]:
df = pd.read_csv("./ficheros_pandas/info_tiburones.csv")
df.head(3)

,case_number,Fatal (Y/N),Injury,Date,year,type,country,area,location,activity,name,sex_,age,time,species_,href,Investigator or Source,pdf,href formula,Case Number.1,Case Number.2,original order
0,2018.06.25,N,"No injury to occupant, outrigger canoe and pad...",25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,18h00,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN
1,2018.06.18,N,Minor injury to left thigh,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,14h00 -15h00,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN
2,2018.06.09,N,Injury to left lower leg from surfboard skeg,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,07h45,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Ejercicio 1. Cread una columna nueva y una función que nos de el mes donde ocurrió el ataque. 
# Tened en cuenta que no todas las filas tienen la misma estructura y que puede que no haya la información de mes. 
# En ese caso devolved un nulo (NaN).

In [5]:
patron = "[\d]-[A-Z].*[a-z]-[\d]"
patron2 = "[A-Z].*[a-z]"

In [4]:
lista= []

In [5]:
len(lista)

0

In [6]:
for i in df["Date"]:    
    lista.append(re.findall(patron, i))

In [7]:
len(lista)

6286

In [8]:
lista2 = []

for i in range(0, len(lista)):
    if len(lista[i]) > 0:
        lista2.append(re.findall(patron2, lista[i][0])[0])
    else: 
        lista2.append("Nan")
        
df["mes"] = lista2

In [25]:
def cambiar_mes(x):
    patron = "[\d]-[A-Z].*[a-z]-[\d]"
    patron2 = "[A-Z].*[a-z]"
    re.findall(patron, x)
    if len(re.findall(patron, x)) > 0:
        return re.findall(patron2, x)[0]
    else: 
        return np.nan

In [26]:
df["mes"] =df["Date"].apply(cambiar_mes)

In [27]:
df

,case_number,Fatal (Y/N),Injury,Date,year,type,country,area,location,activity,name,sex_,age,time,species_,href,Investigator or Source,pdf,href formula,Case Number.1,Case Number.2,original order,mes,nueva
0,2018.06.25,N,"No injury to occupant, outrigger canoe and pad...",25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,18h00,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN,Jun,n
1,2018.06.18,N,Minor injury to left thigh,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,14h00 -15h00,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN,Jun,n
2,2018.06.09,N,Injury to left lower leg from surfboard skeg,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,07h45,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN,Jun,n
3,2018.06.08,N,Minor injury to lower leg,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,NaN,2 m shark,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN,Jun,n
4,2018.06.04,N,Lacerations to leg & hand shark PROVOKED INCIDENT,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,NaN,"Tiger shark, 3m",http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN,Jun,n
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6281,ND.0005,Y,FATAL,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6.0,NaN,y
6282,ND.0004,Y,FATAL,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5.0,NaN,y
6283,ND.0003,Y,FATAL,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4.0,NaN,y
6284,ND.0002,Y,FATAL,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3.0,NaN,y
6285,ND.0001,Y,"FATAL. ""Shark bit him in half, carrying away t...",1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0,NaN,y

In [ ]:
# Ejercicio 2. Vamos con la columna fatal_(y/n). Lo primero que tenéis que hacer es evaluar los valores únicos que hay. 
# Esperaríamos tener solo dos valores: y y n, pero tristemente no debería ser así 😭. 
# Cread una columna nueva y una función que devuelva únicamente y o n y que devuelva un nulo (NaN) si no se encuentra el valor

In [11]:
df["Fatal (Y/N)"].unique()

array(['N', 'Y', nan, 'M', 'UNKNOWN', '2017', ' N', 'N ', 'y'],
      dtype=object)

In [20]:
def limpiar(x):
    if type(x) == str:
        limpio = x.strip().lower()
        if limpio == "y":
            return "y"
        elif limpio == "n":
            return "n"
        else:
            return np.nan            
    else:
        return np.nan

In [40]:
df["muerte"] =df["Fatal (Y/N)"].apply(limpiar)

In [ ]:
# Ejercicio 3. Seguid la misma lógica que en el ejercicio anterior pero con la columna sex. 
# Pero en este caso vamos a incluir un retito más: En este caso querremos tener dos valores únicos F y M. 
# De nuevo en la columna hay otros carácteres raros como 'M ', 'lli', 'N', '.'. 
# En esos casos, queremos que se reemplacen por M o F de forma aleatoria (tendréis que usar la librería random). 
# En caso de que sea nulo, que la función devuelva nulo (np.nan)

In [28]:
df["sex_"].unique()

array(['F', 'M', nan, 'M ', 'lli', 'N', '.'], dtype=object)

In [37]:
def sexar(x):
    aleatorio = random.randint(0,1)
    
    if aleatorio == 0:
        valor = "f"
    else:
        valor = "m"
    
    if type(x) == str:
        limpio = x.strip().lower()
        if limpio == "f":
            return "f"
        elif limpio == "m":
            return "m"
        else:
            return valor  
    else:
        return valor

In [38]:
df["sexo"] =df["sex_"].apply(sexar)

In [41]:
df

,case_number,Fatal (Y/N),Injury,Date,year,type,country,area,location,activity,name,sex_,age,time,species_,href,Investigator or Source,pdf,href formula,Case Number.1,Case Number.2,original order,mes,nueva,sexo,muerte
0,2018.06.25,N,"No injury to occupant, outrigger canoe and pad...",25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,18h00,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN,Jun,n,f,m
1,2018.06.18,N,Minor injury to left thigh,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,14h00 -15h00,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN,Jun,n,f,f
2,2018.06.09,N,Injury to left lower leg from surfboard skeg,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,07h45,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN,Jun,n,m,f
3,2018.06.08,N,Minor injury to lower leg,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,NaN,2 m shark,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN,Jun,n,m,m
4,2018.06.04,N,Lacerations to leg & hand shark PROVOKED INCIDENT,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,NaN,"Tiger shark, 3m",http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN,Jun,n,m,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6281,ND.0005,Y,FATAL,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6.0,NaN,y,m,m
6282,ND.0004,Y,FATAL,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5.0,NaN,y,m,m
6283,ND.0003,Y,FATAL,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4.0,NaN,y,m,m
6284,ND.0002,Y,FATAL,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3.0,NaN,y,m,m
6285,ND.0001,Y,"FATAL. ""Shark bit him in half, carrying away t...",1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0,NaN,y,m,f

In [ ]:
# Ejercicio 4. Una vez que hayáis terminado eliminad las columnas originales conservando las nuevas.

In [44]:
df = df.drop(["Fatal (Y/N)", "sex_"], axis = 1)

In [45]:
df

,case_number,Injury,Date,year,type,country,area,location,activity,name,age,time,species_,href,Investigator or Source,pdf,href formula,Case Number.1,Case Number.2,original order,mes,sexo,muerte
0,2018.06.25,"No injury to occupant, outrigger canoe and pad...",25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,57,18h00,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN,Jun,f,m
1,2018.06.18,Minor injury to left thigh,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,11,14h00 -15h00,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN,Jun,f,f
2,2018.06.09,Injury to left lower leg from surfboard skeg,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,48,07h45,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN,Jun,m,f
3,2018.06.08,Minor injury to lower leg,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,NaN,NaN,2 m shark,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN,Jun,m,m
4,2018.06.04,Lacerations to leg & hand shark PROVOKED INCIDENT,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,NaN,NaN,"Tiger shark, 3m",http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN,Jun,m,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6281,ND.0005,FATAL,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6.0,NaN,m,m
6282,ND.0004,FATAL,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5.0,NaN,m,m
6283,ND.0003,FATAL,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4.0,NaN,m,m
6284,ND.0002,FATAL,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3.0,NaN,m,m
6285,ND.0001,"FATAL. ""Shark bit him in half, carrying away t...",1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,15,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0,NaN,m,f

In [ ]:
# Ejercicio 5. Guardad el dataframe en un csv que usaremos más adelante

In [47]:
df.to_csv("./ficheros_pandas/tiburoncitos.csv")