In [1]:
import pandas as pd
pd.options.display.max_columns = None
import numpy as np
import re
import random as random

In [10]:
df = pd.read_csv("./ficheros_pandas/info_tiburones.csv")
df.head(3)

,case_number,Fatal (Y/N),Injury,Date,year,type,country,area,location,activity,name,sex_,age,time,species_,href,Investigator or Source,pdf,href formula,Case Number.1,Case Number.2,original order
0,2018.06.25,N,"No injury to occupant, outrigger canoe and pad...",25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,18h00,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN
1,2018.06.18,N,Minor injury to left thigh,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,14h00 -15h00,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN
2,2018.06.09,N,Injury to left lower leg from surfboard skeg,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,07h45,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Ejercicio 1. Cread una columna nueva y una función que nos de el mes donde ocurrió el ataque. 
# Tened en cuenta que no todas las filas tienen la misma estructura y que puede que no haya la información de mes. 
# En ese caso devolved un nulo (NaN).

In [11]:
# Primero intentamos hacer la lógica con bucle for
patron = "[\d]-[A-Z].*[a-z]-[\d]"
patron2 = "[A-Z].*[a-z]"
lista= []
lista2 = []

In [6]:
for i in df["Date"]:    
    lista.append(re.findall(patron, i))

In [8]:
for i in range(0, len(lista)):
    if len(lista[i]) > 0:
        lista2.append(re.findall(patron2, lista[i][0])[0])
    else: 
        lista2.append("Nan")
        
df["mes"] = lista2

In [12]:
# Ahora ya creamos la función

def cambiar_mes(x):
    patron = "[\d]-[A-Z].*[a-z]-[\d]"
    patron2 = "[A-Z].*[a-z]"
    re.findall(patron, x)
    if len(re.findall(patron, x)) > 0:
        return re.findall(patron2, x)[0]
    else: 
        return np.nan

In [13]:
df["mes"] =df["Date"].apply(cambiar_mes)
df.head()

,case_number,Fatal (Y/N),Injury,Date,year,type,country,area,location,activity,name,sex_,age,time,species_,href,Investigator or Source,pdf,href formula,Case Number.1,Case Number.2,original order,mes
0,2018.06.25,N,"No injury to occupant, outrigger canoe and pad...",25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,18h00,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN,Jun
1,2018.06.18,N,Minor injury to left thigh,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,14h00 -15h00,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN,Jun
2,2018.06.09,N,Injury to left lower leg from surfboard skeg,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,07h45,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN,Jun
3,2018.06.08,N,Minor injury to lower leg,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,NaN,2 m shark,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN,Jun
4,2018.06.04,N,Lacerations to leg & hand shark PROVOKED INCIDENT,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,NaN,"Tiger shark, 3m",http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN,Jun

In [ ]:
# Ejercicio 2. Vamos con la columna fatal_(y/n). Lo primero que tenéis que hacer es evaluar los valores únicos que hay. 
# Esperaríamos tener solo dos valores: y y n, pero tristemente no debería ser así 😭. 
# Cread una columna nueva y una función que devuelva únicamente y o n y que devuelva un nulo (NaN) si no se encuentra el valor

In [14]:
df["Fatal (Y/N)"].unique()

array(['N', 'Y', nan, 'M', 'UNKNOWN', '2017', ' N', 'N ', 'y'],
      dtype=object)

In [16]:
def limpiar(x):
    if type(x) == str:
        limpio = x.strip().lower()
        if limpio == "y":
            return "y"
        elif limpio == "n":
            return "n"
        else:
            return np.nan            
    else:
        return np.nan

In [17]:
df["muerte"] =df["Fatal (Y/N)"].apply(limpiar)

In [ ]:
# Ejercicio 3. Seguid la misma lógica que en el ejercicio anterior pero con la columna sex. 
# Pero en este caso vamos a incluir un retito más: En este caso querremos tener dos valores únicos F y M. 
# De nuevo en la columna hay otros carácteres raros como 'M ', 'lli', 'N', '.'. 
# En esos casos, queremos que se reemplacen por M o F de forma aleatoria (tendréis que usar la librería random). 
# En caso de que sea nulo, que la función devuelva nulo (np.nan)

In [18]:
df["sex_"].unique()

array(['F', 'M', nan, 'M ', 'lli', 'N', '.'], dtype=object)

In [19]:
def sexar(x):
    aleatorio = random.randint(0,1)
    
    if aleatorio == 0:
        valor = "f"
    else:
        valor = "m"
    
    if type(x) == str:
        limpio = x.strip().lower()
        if limpio == "f":
            return "f"
        elif limpio == "m":
            return "m"
        else:
            return valor  
    else:
        return valor

In [20]:
df["sexo"] =df["sex_"].apply(sexar)

In [21]:
df.head()

,case_number,Fatal (Y/N),Injury,Date,year,type,country,area,location,activity,name,sex_,age,time,species_,href,Investigator or Source,pdf,href formula,Case Number.1,Case Number.2,original order,mes,muerte,sexo
0,2018.06.25,N,"No injury to occupant, outrigger canoe and pad...",25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,18h00,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN,Jun,n,f
1,2018.06.18,N,Minor injury to left thigh,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,14h00 -15h00,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN,Jun,n,f
2,2018.06.09,N,Injury to left lower leg from surfboard skeg,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,07h45,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN,Jun,n,m
3,2018.06.08,N,Minor injury to lower leg,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,NaN,2 m shark,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN,Jun,n,m
4,2018.06.04,N,Lacerations to leg & hand shark PROVOKED INCIDENT,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,NaN,"Tiger shark, 3m",http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN,Jun,n,m

In [ ]:
# Ejercicio 4. Una vez que hayáis terminado eliminad las columnas originales conservando las nuevas.

In [22]:
df = df.drop(["Fatal (Y/N)", "sex_"], axis = 1)
df.head()

,case_number,Injury,Date,year,type,country,area,location,activity,name,age,time,species_,href,Investigator or Source,pdf,href formula,Case Number.1,Case Number.2,original order,mes,muerte,sexo
0,2018.06.25,"No injury to occupant, outrigger canoe and pad...",25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,57,18h00,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN,Jun,n,f
1,2018.06.18,Minor injury to left thigh,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,11,14h00 -15h00,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN,Jun,n,f
2,2018.06.09,Injury to left lower leg from surfboard skeg,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,48,07h45,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN,Jun,n,m
3,2018.06.08,Minor injury to lower leg,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,NaN,NaN,2 m shark,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN,Jun,n,m
4,2018.06.04,Lacerations to leg & hand shark PROVOKED INCIDENT,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,NaN,NaN,"Tiger shark, 3m",http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN,Jun,n,m

In [ ]:
# Ejercicio 5. Guardad el dataframe en un csv que usaremos más adelante

In [47]:
df.to_csv("./ficheros_pandas/tiburoncitos.csv")