In [1]:
import pandas as pd

In [ ]:
# Ejercicio

# En este ejercicio de pair programming pondremos en práctica como cargar distintos tipos de archivos en Python usando Pandas.

# Id cargando todos los ficheros en vuestro jupyter

In [23]:
archivo_csv = pd.read_csv("./ficheros_pandas/quejas.csv", encoding = 'ISO-8859-1', sep = ";")
archivo_csv

,tipo,estado,canal_entrada,fecha_entrada,fecha_contestacion,consejeria,unidad_descripcion,tema,subtema
0,Queja,Recepcionada por Unidad,INTERNET,2022-01-28 00:00:00,NaN,"Consejería de Medio Ambiente, Vivienda y Agric...",D.G. de Descarbonización y Transición Energética,ENERGÍA,NaN
1,Queja,Recepcionada por Unidad,INTERNET,2022-03-28 00:00:00,NaN,"Consejería de Medio Ambiente, Vivienda y Agric...",D.G. de Descarbonización y Transición Energética,ENERGÍA,NaN
2,Queja,Recepcionada por Unidad,INTERNET,2022-03-23 00:00:00,NaN,"Consejería de Medio Ambiente, Vivienda y Agric...",D.G. de Descarbonización y Transición Energética,ENERGÍA,NaN
3,Queja,Recepcionada por Unidad,INTERNET,2022-01-24 00:00:00,NaN,"Consejería de Medio Ambiente, Vivienda y Agric...",D.G. de Descarbonización y Transición Energética,ENERGÍA,NaN
4,Queja,Recepcionada por Unidad,INTERNET,2022-03-29 00:00:00,NaN,"Consejería de Medio Ambiente, Vivienda y Agric...",D.G. de Descarbonización y Transición Energética,ENERGÍA,NaN
...,...,...,...,...,...,...,...,...,...
4494,Sugerencia,Cancelada,INTERNET,2022-01-02 00:00:00,NaN,"Consejería de Medio Ambiente, Vivienda y Agric...",NaN,OTROS,OTROS
4495,Sugerencia,Rechazada por SGAC,INTERNET,2022-03-08 00:00:00,NaN,NaN,NaN,OTROS,Sin valor
4496,Queja,Rechazada por SGAC,INTERNET,2022-01-24 00:00:00,NaN,NaN,NaN,OTROS,Sin valor
4497,Queja,Rechazada por SGAC,INTERNET,2022-01-21 00:00:00,NaN,NaN,NaN,OTROS,Sin valor
4498,Queja,Rechazada por SGAC,INTERNET,2022-01-21 00:00:00,NaN,NaN,NaN,OTROS,Sin valor

In [16]:
archivo_json = pd.read_json("./ficheros_pandas/quejas.json")
archivo_json

                                                   data
0     {'unidad_descripcion': 'D.G. de Descarbonizaci...
1     {'unidad_descripcion': 'D.G. de Descarbonizaci...
2     {'unidad_descripcion': 'D.G. de Descarbonizaci...
3     {'unidad_descripcion': 'D.G. de Descarbonizaci...
4     {'unidad_descripcion': 'D.G. de Descarbonizaci...
...                                                 ...
4442  {'unidad_descripcion': '', 'tipo': 'Sugerencia...
4443  {'unidad_descripcion': '', 'tipo': 'Sugerencia...
4444  {'unidad_descripcion': '', 'tipo': 'Queja', 'e...
4445  {'unidad_descripcion': '', 'tipo': 'Queja', 'e...
4446  {'unidad_descripcion': '', 'tipo': 'Queja', 'e...

[4447 rows x 1 columns]

In [19]:
archivo_xlsx = pd.read_excel("./ficheros_pandas/quejas2.xlsx")
archivo_xlsx

          DESCRIPCION_TEMA                                DESCRIPCION_SUBTEMA
0    ATENCIÓN AL CIUDADANO                         ADMINISTRACIÓN ELECTRÓNICA
1    ATENCIÓN AL CIUDADANO                                    FUNCIÓN PÚBLICA
2    ATENCIÓN AL CIUDADANO  OFICINAS DE ATENCIÓN AL CIUDADANO DE LA COMUNI...
3    ATENCIÓN AL CIUDADANO     OFICINAS DE REGISTRO DE LA COMUNIDAD DE MADRID
4    ATENCIÓN AL CIUDADANO                                              OTROS
..                     ...                                                ...
179               VIVIENDA                                       PLAN ALQUILA
180               VIVIENDA                             PLAN DE VIVIENDA JOVEN
181               VIVIENDA                                 PORTAL DE VIVIENDA
182               VIVIENDA                   PUNTOS DE INFORMACIÓN Y REGISTRO
183               VIVIENDA                                VIVIENDAS DEL IVIMA

[184 rows x 2 columns]

In [39]:
archivo_pickle = pd.read_pickle("./ficheros_pandas/algas.pickle")
archivo_pickle

AttributeError: Can't get attribute '_unpickle_block' on <module 'pandas._libs.internals' from '/Users/luciacernuda/opt/anaconda3/lib/python3.9/site-packages/pandas/_libs/internals.cpython-39-darwin.so'>

In [ ]:
# Para poner el práctica el read_clipboard elegir alguna tabla que os podaís encontrar en google y usad dicho método para traer los datos al jupyter notebook. 
# Una vez que los hayáis cargado, guardad esos datos en los siguientes formatos:

In [30]:
rayos = pd.read_clipboard()
rayos

   00:00  -  02:00  0  0.1
0  02:00  -  04:00  0    0
1  04:00  -  06:00  0    0

In [32]:
rayos.to_csv("./ficheros_pandas/rayos/rayos.csv")

In [33]:
rayos.to_excel("./ficheros_pandas/rayos/rayos.xlsx")

In [35]:
rayos.to_json("./ficheros_pandas/rayos/rayos.json")

In [40]:
rayos.to_pickle("./ficheros_pandas/rayos/rayos.pickle")

In [43]:
#Probamos aquí a abrir un archivo pickle porque algas.pickle nos da error

rayos_pickle = pd.read_pickle("./ficheros_pandas/rayos/rayos.pickle")
rayos_pickle

   00:00  -  02:00  0  0.1
0  02:00  -  04:00  0    0
1  04:00  -  06:00  0    0

In [62]:
#Prueba de otro clipboard

candieira = pd.read_clipboard(sep = "\t")
candieira

,Código validación,Data,Código parámetro,Parámetro,Valor,Unidades
0,1,2022-08-22 00:10:00.0,BCN_AVG_1.5m,Brillo do Ceo Nocturno,19.898,mag/arsec2
1,1,2022-08-22 00:10:00.0,PP_SUM_1.5m,Chuvia,0.000,L/m2
2,1,2022-08-22 00:10:00.0,DV_SD_2m,Desviación típica da dirección do vento a 2m,16.000,º
3,1,2022-08-22 00:10:00.0,VV_SD_2m,Desviación típica da velocidade do vento a 2m,1.800,km/h
4,1,2022-08-22 00:10:00.0,DV_CONDICION_2m,Dirección do refacho a 2m,58.000,º
5,1,2022-08-22 00:10:00.0,DV_AVG_2m,Dirección do vento a 2m,41.000,º
6,1,2022-08-22 00:10:00.0,HF_SUM_2m,Horas humidade foliar,0.000,h
7,1,2022-08-22 00:10:00.0,HS_CV_AVG_-0.2m,Humidade do solo,74.000,m3/m3
8,1,2022-08-22 00:10:00.0,HR_AVG_1.5m,Humidade relativa media a 1.5m,94.000,%
9,1,2022-08-22 00:10:00.0,PR_AVG_1.5m,Presión,979.080,hPa
10,1,2022-08-22 00:10:00.0,PRED_AVG_1.5m,Presión reducida,1022.430,hPa
11,1,2022-08-22 00:10:00.0,VV_RACHA_2m,Refacho a 2m,19.100,km/h
12,1,2022-08-22 00:10:00.0,TO_AVG_1.5m,Temperatura de orballo a 1.5m,15.580,ºC
13,1,2022-08-22 00:10:00.0,TS_AVG_-0.1m,Temperatura do solo a -0.1m,20.180,ºC